---
# icon: pen-to-square
date: 2024-7-23
order: 3
category:
    - Promise
---

# 手写 Promise

### 1、基础版 Promise

-   **例子**：

```js
let p = new Promise((resolve, reject) => {
    // throw new Error("error")
    resolve(1)
    reject(2) // 不会执行，因为Promise的状态只能修改一次
})
```

-   **需求分析**：
    -   Promise 是一个构造函数，调用时需要传入一个回调函数，函数接受两个参数，resolve 代表成功时回调, reject 表示失败时回调。
    -   Promise 里的回调只会执行一个，因为 Promise 的状态只能修改一次
    -   不管是 resolve 还是 reject 回调，都接受一个参数，代表 Promise 执行结果

```js
class myPromise {
    state = "padding" // Promise状态
    result = undefined // Promise结果

    constructor(callback) {
        // 成功时执行回调，将Promise状态改成 fulfilled ，保存传入的结果
        const resolve = (res) => {
            this.state = "fulfilled"
            this.result = res
            console.log(res)
        }

        // 失败时执行回调，将Promise状态改成 rejected ，保存传入的结果
        const reject = (err) => {
            this.state = "rejected"
            this.result = err
            console.log(err)
        }

        callback(resolve, reject) // 回调执行
    }
}

const p1 = new myPromise((resolve, reject) => {
    resolve(1)
    reject(2)
    // throw new Error("error")
})

// 输出 1 2
```

上面的代码有些许问题：

1. resolve 和 reject 都被执行了，不符合状态只能修改一次的需求
2. 然后就是修改状态和保存代码可以复用，需要提取一下
3. Promise 报错没有处理，正常 Promise 报错是走 reject 逻辑的

```js
// 解释：把状态提取出来,便于维护
const PENDING = "pending"
const FULFILLED = "fulfilled"
const REJECTED = "rejected"

class myPromise {
    #state = PENDING // 私有属性，Promise状态
    #result = undefined // 私有属性，Promise结果

    constructor(callback) {
        // 成功时执行回调，将Promise状态改成 fulfilled ，保存传入的结果
        const resolve = (res) => {
            // this.state = "fulfilled"
            // this.result = res
            this.#changeState(FULFILLED, res)
        }

        // 失败时执行回调，将Promise状态改成 rejected ，保存传入的结果
        const reject = (err) => {
            // this.state = "rejected"
            // this.result = err
            this.#changeState(REJECTED, err)
        }

        // 解释：处理Promise执行出错，直接reject
        try {
            callback(resolve, reject)
        } catch {
            reject(err)
        }
    }

    // 解释：resolve和reject都要修改状态和返回结果，提取出来
    #changeState(state, res) {
        if (this.#state !== PENDING) return // 解释：状态只能修改一次,也就是只能从pending变为其他状态
        this.#state = state
        this.#result = res
        console.log(res)
    }
}

const p1 = new myPromise((resolve, reject) => {
    resolve(1)
    reject(2)
    // throw new Error("error")
})
// 输出 1 ， throw new Error的问题也处理了
```

### 2、then 方法以及链式调用

-   **例子**

```js
const p = new Promise((resolve, reject) => {
    resolve(5)
})
    .then((res) => {
        console.log(res) // 输出5
        return res * 2
    })
    .then((res) => {
        console.log(res) // 输出10
    })

const p = new myPromise((resolve, reject) => {
    resolve(5)
}).then(
    (res) => {
        console.log("success", res) // Promise resolve的时候执行
    },
    (err) => {
        console.log("err", err) // Promise reject的时候执行
    }
)
```

-   **需求分析**
    -   then 是微任务，需要创建微任务队列，先进先出。
    -   then 每次返回新的 Promise
    -   then 函数接受两个参数 onFullFilled, onRejected，这两个参数分别代表 then 执行成功和 then 执行失败

```js
// 解释：把状态提取出来,便于维护
const PENDING = "pending"
const FULFILLED = "fulfilled"
const REJECTED = "rejected"

class myPromise {
    #state = PENDING // 私有属性，Promise状态
    #result = undefined // 私有属性，Promise结果

    constructor(callback) {
        // 成功时执行回调，将Promise状态改成 fulfilled ，保存传入的结果
        const resolve = (res) => {
            // this.state = "fulfilled"
            // this.result = res
            this.#changeState(FULFILLED, res)
        }

        // 失败时执行回调，将Promise状态改成 rejected ，保存传入的结果
        const reject = (err) => {
            // this.state = "rejected"
            // this.result = err
            this.#changeState(REJECTED, err)
        }

        // 解释：处理Promise执行出错，直接reject
        try {
            callback(resolve, reject)
        } catch {
            reject(err)
        }
    }

    // 解释：resolve和reject都要修改状态和返回结果，提取出来
    #changeState(state, res) {
        if (this.#state !== PENDING) return // 解释：状态只能修改一次,也就是只能从pending变为其他状态
        this.#state = state
        this.#result = res
    }

    // 解释：then方法，接受两个参数成功或失败的回调，返回一个Promise
    then(onFulfilled, onRejected) {
        if (this.#state === FULFILLED) {
            onFulfilled(this.#result) // 解释：Promise resolve的时候执行
        } else if (this.#state === REJECTED) {
            onRejected(this.#result) // 解释：Promise reject的时候执行
        } else {
            // 解释：Promise pending的时候，将回调函数保存起来，等状态改变的时候执行
        }
    }
}

const p = new myPromise((resolve, reject) => {
    setTimeout(() => {
        resolve(5)
    }, 1000) // 模拟异步操作，1秒后resolve，也就是1秒后修改Promise状态，但是上面then方法没有处理padding的逻辑
}).then(
    (res) => {
        console.log("success", res) // Promise resolve的时候执行
    },
    (err) => {
        console.log("err", err) // Promise reject的时候执行
    }
)
```

上面的代码实现了 then 方法的成功和失败回调，但是如果遇到异步操作，也就是 Promise 进入 padding 的时候，就没有执行了，所以需要修改

```js
// 解释：把状态提取出来,便于维护
const PENDING = "pending"
const FULFILLED = "fulfilled"
const REJECTED = "rejected"

class myPromise {
    #state = PENDING // 私有属性，Promise状态
    #result = undefined // 私有属性，Promise结果
    #handlers = [] // 私有属性，保存then方法传入的回调函数

    constructor(callback) {
        // 成功时执行回调，将Promise状态改成 fulfilled ，保存传入的结果
        const resolve = (res) => {
            // this.state = "fulfilled"
            // this.result = res
            this.#changeState(FULFILLED, res)
        }

        // 失败时执行回调，将Promise状态改成 rejected ，保存传入的结果
        const reject = (err) => {
            // this.state = "rejected"
            // this.result = err
            this.#changeState(REJECTED, err)
        }

        // 解释：处理Promise执行出错，直接reject
        try {
            callback(resolve, reject)
        } catch {
            reject(err)
        }
    }

    // 解释：resolve和reject都要修改状态和返回结果，提取出来
    #changeState(state, res) {
        if (this.#state !== PENDING) return // 解释：状态只能修改一次,也就是只能从pending变为其他状态
        this.#state = state
        this.#result = res

        // 解释：当状态改变的时候，执行then方法传入的回调函数
        this.#runTask()
    }

    // 解释：then方法，接受两个参数成功或失败的回调，返回一个Promise
    then(onFulfilled, onRejected) {
        // 返回一个Promise，方便链式调用
        return new myPromise((resolve, reject) => {
            // 将回调函数保存起来
            this.#handlers.push(() => {
                try {
                    let cb = this.#state === FULFILLED ? onFulfilled : onRejected
                    let res = typeof cb === "function" ? cb(this.#result) : this.#result // onFulfilled/onRejected是可选参数，没传的话，返回上一次的结果
                    // let res = cb(this.#result)
                    resolve(res) // 返回上一个then的结果

                    // if (state === FULFILLED) {
                    //     let res = onFulfilled(res)
                    //     resolve(res) // 返回上一个then的结果
                    // } else if (state === REJECTED) {
                    //     let res = onRejected(res)
                    //     resolve(res) // 返回上一个then的结果
                    // }
                } catch {
                    reject(err) // 返回上一个then reject的结果
                }
            })
            this.#runTask()
        })
    }

    #runTask() {
        // queueMicrotask 注册微任务(有兼容问题)
        queueMicrotask(() => {
            // 解释：当状态改变的时候，执行then方法传入的回调函数
            if (this.#state !== PENDING) {
                this.#handlers.forEach((cb) => cb())
                this.#handlers = [] // 解释：执行完回调后，清空回调函数
            }
        })
    }
}

console.log("start")
const p = new myPromise((resolve, reject) => {
    resolve(5)
})
    .then(
        (res) => {
            console.log("success", res) // 输出 ‘success’ 5
            return res * 2
        },
        (err) => {
            console.log("err", err) // Promise reject的时候执行
        }
    )
    .then((res) => {
        console.log("success2", res) // 输出 ‘success2’ 10
    })

console.log("end")
// 最终输出 start end success 5 success2 10
```

### 3、微任务兼容处理

### 4、catch 方法实现

### 5、all 方法实现
